name: kagayaku_modules
description: Source modules for the kagayaku app.
version: 1.0.4
repository: https://github.com/Zerolmntrix/kagayaku-modules
publish_to: 'none'

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
